version: "2"

formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign

run:
  timeout: 5m
